In [3]:
print ('hi')

hi


Task a

In [4]:
import numpy as np

Task b

In [5]:
b = np.zeros((5,2))
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Task c

In [6]:
c = np.zeros((2,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Task d

In [7]:
d = np.linspace(5,5,10)
print(d)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Task e

In [9]:
e = np.linspace(10,50,41)
print(e)
e2 = np.arange(10,51)
print(e2)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49. 50.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Task f

In [11]:
f = np.arange(10,51,2)
print(f)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Task g

In [12]:
g = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(g)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Task h

In [13]:
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task i

In [14]:
i = np.random.rand()
print(i)

0.9725893931653671


Task j

In [15]:
j = np.random.standard_normal(25)
print(j)

[ 0.22084857  1.71913586  0.35382768  0.01937312 -0.03701493 -0.51351203
 -0.05878931  0.27226138 -0.98670687 -0.82314705  0.72359628 -1.17752345
  0.00489725  0.31538592 -0.68162493 -1.10404509  1.05863646  1.17226181
 -1.38948346 -0.4353235   0.79053025 -0.80804082 -0.99091773  0.62704479
 -0.82377123]


Task k

In [16]:
k = np.linspace(0.01,1,100)
k = k.reshape((10,10))
print(k)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Task l

In [17]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [18]:
lx = mat[2:5]
l = np.delete(lx,0,axis=1)
print(l)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Task m

In [19]:
m = mat[3][4]
print(m)

20


Task n

In [20]:
mat = np.array(mat)
nx = mat[0:3,1]
n=nx.reshape((3,1))
print(n)

[[ 2]
 [ 7]
 [12]]


Task o

In [22]:
o = mat[:][4]
print(o)

[21 22 23 24 25]


Task p

In [26]:
p = mat[:][3:5]
print(p)

[[16 17 18 19 20]
 [21 22 23 24 25]]


Task q

In [28]:
q = np.sum(mat)
print(q)

325


Task r

In [29]:
r = np.std(mat)
print(r)

7.211102550927978


Task s

In [32]:
s = np.sum(mat,axis=0)
print(s)

[55 60 65 70 75]
